### ISSUE TITLE
without print when using `output` flag

### ISSUE THREAD

**Issue by mrxiaozhuox** [fj0r/ai.nu#1]
I want use Nushell to handle all of the result, so is there any flag can be disable print? (for ollama chat)

Normally, I think that once there is `output`, the content of print should be directly blocked.

**Comment by orbsh** [comment]
ok, already fixed. Or you can directly use `ai-chat`
In fact, ollama is also compatible with the openai interface
Now it mainly focuses on the openai api

**Comment by mrxiaozhuox** [comment]
Thanks!
